name: Docker Image CI

on:
  workflow_run:
    workflows: [Build & Test]
    types:
      - completed

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag github.com/thurse93/german-angst-api:$(date +%s)
    - name: Deploy Docker Image to thurse.de
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.GERMAN_ANGST_API_DEPLOYMENT_KEY }}
        port: ${{ secrets.PORT }}
        script: whoami
